### ISSUE TITLE
Connect to Oracle error

### ISSUE THREAD

**Issue by qiuqiuqiuqiuqiuqiu** [socialpoint-labs/sqlbucket#24]
Hi, 

Does this project support Oracle connection? Or how can I set the connection?

I set connections as below
connections = {'conn': 'oracle+cx_oracle://name:passwd@ip:port/dbname'}

When I run the project , got error "TypeError: Invalid argument(s) 'isolation_level' sent to create_engine(), using configuration OracleDialect_cx_oracle/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
"
Seems the isolation_level is fixed to "AUTOCOMMIT" in create_connection(runners.py).

Thanks

**Comment by philippe2803** [comment]
@qiuqiuqiuqiuqiuqiu 
SQLbucket uses SQLAlchemy under the hood, and Oracle can definitely work with it, so you should be able to use Oracle for sure. I set `AUTOCOMMIT` as default some time ago though but realized this isolation level is definitely not valid for most databases... so this needs to be changed for sure.

I should be able to do a hotfix in the next few days though. Would you like control on the isolation level to use and have it as a parameter?

**Comment by qiuqiuqiuqiuqiuqiu** [comment]
@philippe2803 
Thank you very much for quick response.
Sure, have isolation level as a parameter with default value is a good choice.

Regards Qiu

**Comment by philippe2803** [comment]
Made a PR yesterday. This is being reviewed as we speak: https://github.com/socialpoint-labs/sqlbucket/pull/25

**Comment by qiuqiuqiuqiuqiuqiu** [comment]
Hi @philippe2803 

How should I configure the connection for oracle db after the change.
I configured the connection to oracle db as below.
`connections = {
    'db_zx': 'oracle+cx_oracle://center_edb:timegao@168.61.2.2:1521/servdb?isolation_level=READ COMMITTED'
}`
Still got the error
TypeError: Invalid argument(s) 'isolation_level' sent to create_engine(), using configuration OracleDialect_cx_oracle/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

Regards Qiu

**Comment by philippe2803** [comment]
@qiuqiuqiuqiuqiuqiu 
The library is not updated yet with the changes. It should be at some point this week. In the meantime, you could try with the current development package. You just need to uninstall sqlbucket and re-install a dev package that I created for test purposes.

```bash
pip uninstall sqlbucket
pip install sqlbucket==0.3.3.dev3
```

`READ COMMITTED` is the default isolation level for oracle, and therefore will be the one applied by default. So, in your case, you won't need to set isolation level anymore.

**Comment by philippe2803** [comment]
closing as this has been sorted.
